# Generated by Django 3.0.2 on 2020-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='tested',
            field=models.BooleanField(default=False, verbose_name='Протестирован?'),
        ),
    ]
