# Generated by Django 3.0.2 on 2020-01-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_candidate_tested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('created',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
