# Generated by Django 3.0.2 on 2020-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_candidate_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='result',
            field=models.CharField(blank=True, max_length=254, verbose_name='Варианты ответов'),
        ),
    ]
